version = 5.5.0
archive_dir = /etc/letsencrypt/archive/easytaxiisrael.com
cert = /etc/letsencrypt/live/easytaxiisrael.com/cert.pem
privkey = /etc/letsencrypt/live/easytaxiisrael.com/privkey.pem
chain = /etc/letsencrypt/live/easytaxiisrael.com/chain.pem
fullchain = /etc/letsencrypt/live/easytaxiisrael.com/fullchain.pem
[renewalparams]
account = 9813b9ebc8a9a62ce86df79bd4592056
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
